apiVersion: skaffold/v1beta1
kind: Config
build:
  artifacts:
  - image: hub.docker.com/yaleits/ecsapi
    docker:
      dockerfile: k8s/Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/k8s-*
