# build stage
FROM golang:alpine AS build-env

RUN apk add --no-cache git openssh-client gcc musl-dev

WORKDIR /go
ENV GOPATH=/go
ENV GO111MODULE=on
RUN go version
ADD . /go/src/git.yale.edu/spinup/ecs-api/
RUN cd /go/src/git.yale.edu/spinup/ecs-api && go get ./...
RUN cd /go/src/git.yale.edu/spinup/ecs-api && go build -o /go/api *.go

# final stage
FROM alpine
RUN apk add --no-cache ca-certificates
WORKDIR /app
COPY --from=build-env /go/api /app/api
EXPOSE 80
ENTRYPOINT ["./api"]
